base_url = "https://kooistracs.nl"
title = "Kooistra Cyber Solutions"
author = "Connor Kooistra"

compile_sass = true
build_search_index = false

[extra]
github = "https://github.com/kooistracs"
linkedin = "https://www.linkedin.com/company/kooistracs/"
email = "contact@kooistracs.nl"
