# base_url = "https://kooistracs.nl"
base_url = "https://kooistracs.github.io/kooistracs.nl/"
title = "KCS"
description = "Kooistra Cyber Solutions"
author = "Connor Kooistra"

compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
