on:
    push:
        branches:
            - main
    repository_dispatch:
        types: [update_readme]

name: Build and Deploy GH Pages

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Fetch GitHub README
              run: |
                  curl -s https://raw.githubusercontent.com/cdkooistra/cdkooistra/main/README.md > latest_readme.md

            - name: Check README for changes
              id: readme_check
              run: |
                  if [[ -f content/readme.md && "$(cat content/readme.md)" == "$(cat latest_readme.md)" ]]; then
                      echo "README has not changed. Skipping build."
                      exit 0
                  fi
                  echo "---" > content/readme.md
                  echo "title: GitHub README" >> content/readme.md
                  echo "date: $(date -I)" >> content/readme.md
                  echo "template: readme.html" >> content/readme.md
                  echo "---" >> content/readme.md
                  cat latest_readme.md >> content/readme.md

            - name: Build and Deploy with Zola
              if: success()
              uses: shalzz/zola-deploy-action@master
              env:
                  PAGES_BRANCH: gh-pages
                  TOKEN: ${{ secrets.GITHUB_TOKEN }}
